**Cree un programa que seleccione dos vectores de longitud n (dada por el usuario al principio) y halle su producto escalar.**

In [ ]:
x = int(input("Ingresa la longitud del vector: "))

def ingresar():
  vector = []
  for i in range (x):
    num = float(input("Ingresa el número: "))
    vector.append(num)
  return vector

print('\n'"Ingresa el primer vector"'\n')
vector1= ingresar()
print('\n'"Ingresa el segundo vector"'\n')
vector2= ingresar()

vector_escalar = []

for i in range (x):
  producto_escalar = vector1[i] * vector2[i]
  vector_escalar.append(producto_escalar)

print('\n'"El producto escalar entre los vectores es: ", vector_escalar)

Ingresa la longitud del vector: 3

Ingresa el primer vector

Ingresa el número: 2
Ingresa el número: 6
Ingresa el número: 3

Ingresa el segundo vector

Ingresa el número: 2
Ingresa el número: 1
Ingresa el número: 2

El producto escalar entre los vectores es:  [4.0, 6.0, 6.0]


**Cree un programa que solicite dos matrices A y B (las dimesiones de cada matriz deben estar indicadas por el usuario) y, de ser posible, reaclice las siguientes operaciones:**

3A

4B

A + B

B x A

In [ ]:
import numpy as np

def solicitar_matriz(nombre_matriz):
    filas = int(input(f"Ingrese el número de filas para la matriz {nombre_matriz}: "))
    columnas = int(input(f"Ingrese el número de columnas para la matriz {nombre_matriz}: "))
    print()

    matriz = []
    for i in range(filas):
        fila = []
        for j in range(columnas):
            num = float(input(f"Ingrese el valor para la fila {i + 1}, columna {j + 1} de la matriz {nombre_matriz}: "))
            fila.append(num)
        matriz.append(fila)
    print()

    return np.array(matriz)

def operaciones(matriz_a,matriz_b):

  producto_escalarA = 3 * matriz_a
  print("Matriz 3A"'\n', producto_escalarA)

  producto_escalarB = 4 * matriz_b
  print('\n'"Matriz 4B"'\n', producto_escalarB)

  if matriz_a.shape == matriz_b.shape:
    suma = matriz_a + matriz_b
    print('\n'"Suma de matrices A + B"'\n', suma)
  else:
    print('\n'"Las matrices no tienen las mismas dimensiones")

  if matriz_b.shape[0] == matriz_a.shape[1]:
    producto_matrices = np.dot(matriz_b, matriz_a)
    print('\n'"Producto de matrices BA"'\n',producto_matrices)
  else:
    print('\n'"La cantidad de columnas de la matriz B debe ser igual a la cantidad de filas de la matriz A")

matriz_a = solicitar_matriz("A")
matriz_b = solicitar_matriz("B")

operaciones(matriz_a,matriz_b)

Ingrese el número de filas para la matriz A: 2
Ingrese el número de columnas para la matriz A: 1

Ingrese el valor para la fila 1, columna 1 de la matriz A: 2
Ingrese el valor para la fila 2, columna 1 de la matriz A: 3

Ingrese el número de filas para la matriz B: 4
Ingrese el número de columnas para la matriz B: 1

Ingrese el valor para la fila 1, columna 1 de la matriz B: 4
Ingrese el valor para la fila 2, columna 1 de la matriz B: 5
Ingrese el valor para la fila 3, columna 1 de la matriz B: 6
Ingrese el valor para la fila 4, columna 1 de la matriz B: 3

Matriz 3A
 [[6.]
 [9.]]

Matriz 4B
 [[16.]
 [20.]
 [24.]
 [12.]]

Las matrices no tienen las mismas dimensiones

La cantidad de columnas de la matriz B debe ser igual a la cantidad de filas de la matriz A


In [17]:
import numpy as np

def solicitar_matriz(nombre_matriz):
    filas = int(input(f"Ingrese el número de filas para la matriz {nombre_matriz}: "))
    columnas = int(input(f"Ingrese el número de columnas para la matriz {nombre_matriz}: "))
    print()

    matriz = []
    for i in range(filas):
        fila = []
        for j in range(columnas):
            num = float(input(f"Ingrese el valor para la fila {i + 1}, columna {j + 1} de la matriz {nombre_matriz}: "))
            fila.append(num)
        matriz.append(fila)
    print()

    return np.array(matriz)

def operaciones(matriz_a,matriz_b):

  producto_escalarA = 3 * matriz_a
  print("Matriz 3A"'\n', producto_escalarA)

  producto_escalarB = 4 * matriz_b
  print('\n'"Matriz 4B"'\n', producto_escalarB)

  if matriz_a.shape == matriz_b.shape:
    suma = matriz_a + matriz_b
    print('\n'"Suma de matrices A + B"'\n', suma)
  else:
    print('\n'"Las matrices no tienen las mismas dimensiones")

  if matriz_b.shape[0] == matriz_a.shape[1]:
    producto_matrices = np.dot(matriz_b, matriz_a)
    print('\n'"Producto de matrices BA"'\n',producto_matrices)
  else:
    print('\n'"La cantidad de columnas de la matriz B debe ser igual a la cantidad de filas de la matriz A")

matriz_a = solicitar_matriz("A")
matriz_b = solicitar_matriz("B")

operaciones(matriz_a,matriz_b)

Ingrese el número de filas para la matriz A: 2
Ingrese el número de columnas para la matriz A: 2

Ingrese el valor para la fila 1, columna 1 de la matriz A: 1
Ingrese el valor para la fila 1, columna 2 de la matriz A: 4
Ingrese el valor para la fila 2, columna 1 de la matriz A: 2
Ingrese el valor para la fila 2, columna 2 de la matriz A: 5

Ingrese el número de filas para la matriz B: 2
Ingrese el número de columnas para la matriz B: 2

Ingrese el valor para la fila 1, columna 1 de la matriz B: 3
Ingrese el valor para la fila 1, columna 2 de la matriz B: 6
Ingrese el valor para la fila 2, columna 1 de la matriz B: 1
Ingrese el valor para la fila 2, columna 2 de la matriz B: 0

Matriz 3A
 [[ 3. 12.]
 [ 6. 15.]]

Matriz 4B
 [[12. 24.]
 [ 4.  0.]]

Suma de matrices A + B
 [[ 4. 10.]
 [ 3.  5.]]

Producto de matrices BA
 [[15. 42.]
 [ 1.  4.]]
