**Cree un programa que, por medio de la eliminación de Gauss-Jordan, halle la inversa de las siguientes matrices:**

A= ( (3,2,2), (3,1,-3), (1,0,-2) )

B= ( (1,2,0,4), (2,0,-1,-2), (1,1,-1,0), (0,4,1,0) )

In [ ]:
import numpy as np

def inversa(matriz, etiqueta):
    n = len(matriz)
    identidad = np.identity(n)
    print("Matriz ",etiqueta,'\n',matriz,'\n','\n'"Identidad"'\n',identidad,'\n')

    matriz_aumentada = np.concatenate((matriz, identidad), axis=1)
    print("Aumento"'\n',matriz_aumentada,'\n')

    for fila_pivote in range(n):
        divisor = matriz_aumentada[fila_pivote, fila_pivote]
        matriz_aumentada[fila_pivote] /= divisor

        for fila_actual in range(n):
            if fila_actual != fila_pivote:
                factor = matriz_aumentada[fila_actual, fila_pivote]
                matriz_aumentada[fila_actual] -= factor * matriz_aumentada[fila_pivote]

    inversa = matriz_aumentada[:, n:]

    return inversa

Matriz_A = np.array([[3, 2, 2], [3, 1, -3], [1, 0, -2]])

Matriz_B = np.array([[1, 2, 0, 4], [2, 0, -1, -2], [1, 1, -1, 0], [0, 4, 1, 0]])

inversa_A = inversa(Matriz_A, "A")
inversa_B = inversa(Matriz_B, "B")

print("Inversa de A:")
print(inversa_A)
print("\nInversa de B:")
print(inversa_B)


Matriz  A 
 [[ 3  2  2]
 [ 3  1 -3]
 [ 1  0 -2]] 
 
Identidad
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Aumento
 [[ 3.  2.  2.  1.  0.  0.]
 [ 3.  1. -3.  0.  1.  0.]
 [ 1.  0. -2.  0.  0.  1.]] 

Matriz  B 
 [[ 1  2  0  4]
 [ 2  0 -1 -2]
 [ 1  1 -1  0]
 [ 0  4  1  0]] 
 
Identidad
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

Aumento
 [[ 1.  2.  0.  4.  1.  0.  0.  0.]
 [ 2.  0. -1. -2.  0.  1.  0.  0.]
 [ 1.  1. -1.  0.  0.  0.  1.  0.]
 [ 0.  4.  1.  0.  0.  0.  0.  1.]] 

Inversa de A:
[[ 1.  -2.   4. ]
 [-1.5  4.  -7.5]
 [ 0.5 -1.   1.5]]

Inversa de B:
[[ 0.33333333  0.66666667 -0.66666667  0.        ]
 [-0.06666667 -0.13333333  0.33333333  0.2       ]
 [ 0.26666667  0.53333333 -1.33333333  0.2       ]
 [ 0.2        -0.1        -0.         -0.1       ]]
